before:
  hooks:
    - go mod download
build:
  goarch:
    - amd64
  env:
    - CGO_ENABLED=0
brews:
- github:
    owner: caarlos0
    name: homebrew-tap
  folder: Formula
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
archives:
  - name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}'
dockers:
  - image_templates:
    - 'caarlos0/version_exporter:latest'
    - 'caarlos0/version_exporter:{{ .Tag }}'
    - 'caarlos0/version_exporter:v{{ .Major }}'
    extra_files:
    - config.yaml
